sudo: required
services:
  - docker

before_install:
  - docker build -t urazov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  urazov/react-test npm test -- --coverage

after_success:
  - docker build -t urazov/multi-client ./client
  - docker build -t urazov/multi-nginx ./nginx
  - docker build -t urazov/multi-server ./server
  - docker build -t urazov/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # takes those images and push them to docker hub
  - docker push urazov/multi-client
  - docker push urazov/multi-nginx
  - docker push urazov/multi-server
  - docker push urazov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-149016107262"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY